config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

 devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
 end

 unauthenticated do
  root 'users#index'
 end

 root 'groups#index', as: 'expense'

 resources :users

 resources :groups, only: %i[index show new create destroy] do
  resources :expenses, only: %i[new show create destroy]
 end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    can :read, all
    if user.role == 'admin'
      can :manage, :all
    else
      can :read, :all
      can :destroy, Group do |group|
        group.user.id == user.id
      end

      can :destroy, Expense do |expense|
        expense.user.id = user.id
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :expenses, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  after_create :set_role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :set_role
  validates :name, presence: true
  validates :email, presence: true

  has_many :groups
  has_many :expenses

  def set_role
    update(role: 'user')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def new
    @user = User.where(user_id: current_user.id)
    @group = Group.find(params[:group_id])
    @expense = Expense.new
  end

  def create
    @group = Group.find(params[:group_id])
    @expenses = @group.expenses.create(name: expense_params[:name], amount: expense_params[:amount],
                                       user_id: current_user.id, group_id: @group.id)
    if @expenses.save
      flash[:notice] = 'Expense created succesfully'
      redirect_to group_path(@group)
    else
      render :new
    end
  end

  def destroy
    @expense = Expense.find(params[:id])
    authorize! :destroy, :expense
    flash[:notice] = if @expense.destroy
                       'Expense deleted'
                     else
                       'An error ocurred'
                     end
    redirect_to root_path
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.where(user_id: current_user.id)
  end

  def show
    @group = Group.find(params[:id])
    @group_expenses = @group.expenses.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.create(group_params)
    if @group.save
      flash[:notice] = 'Category created succesfully'
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @group = Group.find(params[:id])
    authorize! :destroy, @group
    flash[:notice] = if @group.destroy
                       'Category deleted'
                     else
                       'An error ocurred'
                     end
    redirect_to root_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/expenses/new.html.erb
  <nav class='bdtly-navbar'>
    <div class='nav-els-cont d-flex justify-content-between align'>
      <div class='arrow-cont'>
        <a href="/"><i class="fa fa-arrow-left arrow-link" ></i></a>
      </div>
      <div class='current-page-cont'>
        <h1 class='current-page'>NEW EXPENSE</h1>
      </div>
      <div class='login-perm-link-cont'>
            <%= render 'layouts/navbar', class: 'login-perm-link'%>
      </div>
    </div>
  </nav>

<%= form_with model: [@group, @group.expenses.create], class:"input-form", data: { turbo: "false" }  do |f| %>


<div class="">
  <%= f.text_field :name,required: true, class:'b-field', placeholder: "Name", id: ""%><br>
</div>


<div class="">
  <%= f.number_field :amount ,  class:'b-field' , required: true, placeholder: 'Amount',  min: 1%><br>
</div>

<%= f.submit "Create Expense", class:'create-cat-btn  create-exp-btn', data: { turbo: "false" } %>
<%end%>

app/views/groups/index.html.erb
  <nav class='bdtly-navbar'>
    <div class='nav-els-cont d-flex justify-content-between align'>
      <div class='arrow-cont'>
        <a href="/"><i class="fa fa-arrow-left arrow-link" ></i></a>
      </div>
      <div class='current-page-cont'>
        <h1 class='current-page'>CATEGORIES</h1>
      </div>
      <div class='login-perm-link-cont'>
            <%= render 'layouts/navbar', class: 'login-perm-link'%>
      </div>
    </div>
  </nav>


<% if @groups.any? %>
<% @groups.each do |group| %>

    <div class='g-card-cont'>
        <div class='g-card-col-1'>
            <%= image_tag "#{group.icon}", class:'g-card-img' %>
        </div>

        <div class='g-card-col-2 d-flex flex-column'>
            <p><%= link_to group.name, group_path(group), class: 'g-card-name' %></p>
            <%# <p><%= group.created_at.strftime, class: 'g-card-date' %></p>
        </div>

        <div class='g-card-col-3'>
            <p>Total: $<%= group.expenses.sum(:amount) %> </p>
        </div>
    </div>


<% end %>

<% else %>
<p>There are no categories. Please create a new category</p>
<% end %>

<div class='create-g-btn'>
    <%= link_to 'Create New Category', new_group_path, class: 'create-cat-btn' %>
</div>

app/views/groups/new.html.erb
  <nav class='bdtly-navbar'>
    <div class='nav-els-cont d-flex justify-content-between align'>
      <div class='arrow-cont'>
        <a href="/"><i class="fa fa-arrow-left arrow-link" ></i></a>
      </div>
      <div class='current-page-cont'>
        <h1 class='current-page'>CREATE CATEGORY</h1>
      </div>
      <div class='login-perm-link-cont'>
            <%= render 'layouts/navbar', class: 'login-perm-link'%>
      </div>
    </div>
  </nav>


<%= form_with model: @group, class:""  do |f|%>



<div class='new-g-form'>
    <%= f.text_field :name,  required: true,  class: 'b-field', placeholder: "Category Name", id:'name'%><br>

    <%= f.text_field :icon, required: true, class: 'b-field', placeholder: "Enter image link"%>

    <div class='create-g-btn'>
     <%= f.submit "Create Category", class: 'create-cat-btn' %>
    </div>
</div>

<%end%>

app/views/groups/show.html.erb
  <nav class='bdtly-navbar'>
    <div class='nav-els-cont d-flex justify-content-between align'>
      <div class='arrow-cont'>
        <a href="/"><i class="fa fa-arrow-left arrow-link" ></i></a>
      </div>
      <div class='current-page-cont'>
        <h1 class='current-page'>DETAILS</h1>
      </div>
      <div class='login-perm-link-cont'>
            <%= render 'layouts/navbar', class: 'login-perm-link'%>
      </div>
    </div>
  </nav>


<div class='group-details-header'>


    <div class='g-details-cols'>
        <div class='det-col-1'>
            <%= image_tag "#{@group.icon}", class:'g-card-img' %>
        </div>

        <div class='det-col-2'>
            <p class='group-name-head'><%= link_to @group.name, class: 'group-name-link' %></p>
        </div>

    </div>

</div>

    <% if @group.expenses.any? %>
      <div class='g-details-cont'>
        <% @group.expenses.order(created_at: 'DESC').each do |expense| %>

            <div class='exp-card d-flex'>
                <div class='exp-card-col-1'>
                    <p class='expense-name'><%= expense.name %></p>
                    <p class='created_at'>Created at: <%= expense.created_at.strftime("%Y-%b-%d") %></p>
                </div>

                <div class='exp-card-col-2'>
                    <p class='expense-amount'>Amount: $<%= expense.amount %></p>
                </div>
            
            </div>
        <% end %>

      </div>

    <% else %>
        <p>No transaction was made in this category</p>
    <% end %>

    <div class='total-cont'>
      <p class='expense-total-amount'>Total Expenses: $<%= @group.expenses.sum(:amount) %> </p>
    </div>

    <div class='create-g-exp-btn'>
        <%= link_to 'Add expense', new_group_expense_path(@group), class: 'create-exp-btn'  %>
    </div>

app/views/layouts/_navbar.html.erb
   
<% if user_signed_in?%>
  <%= link_to 'Logout', '/users/sign_out', class: 'login-perm-link' %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetlyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/4fa8c393d0.js" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<div class='index-body d-flex flex-column'>
<h2 class='splash-logo'>Budgetly</h2>



<div class='user-sign-cont d-flex flex-column'>
        <button class='sign-btn sign-b'><%= link_to 'Sign in', new_user_session_path, class: 'sign-btn-link-b' %></button>
        <button class='sign-btn'><%= link_to 'Sign up', new_user_registration_path, class: 'sign-btn-link' %></button>
</div>
</div>